import os
import openai
from .markdown_formatter import format_to_markdown

openai.api_key = os.getenv('OPENAI_API_KEY')

def generate_report(log):
    prompt = f"Analyze the following error log and create a structured bug report:\n\n{log}"
    
    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        messages=[
            {"role": "system", "content": "You are a helpful AI that creates bug reports."},
            {"role": "user", "content": prompt}
        ]
    )
    
    content = response['choices'][0]['message']['content']
    
    # Optional: parse response into components (e.g., summary, causes)
    markdown = format_to_markdown(content)
    
    return {
        "summary": "Generated by AI",
        "details": content,
        "markdown": markdown
    }
